destination: ./_site
auto:        false
lsi:         false
server_port: 4000
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

cola_version: "1.9.4"
cola_release_date: "2014-01-30"
cola_downloads: "https://github.com/git-cola/git-cola/releases/download"
cola_archive: "https://github.com/git-cola/git-cola/archive"
cola_github: "https://github.com/git-cola/git-cola"
